name: GCP Terraform Apply

on:
  push:
    branches:
      - "develop"
    paths:
      - "**.tf"
      - ".github/workflows/terraform-cd-dev.yaml"

jobs:
  develop-terraform-cd:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: gcp setup
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "latest"
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.DEV_TERRAFORM_CREDENTIALS }}
          export_default_credentials: true

      - name: set terraform env
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.4

      - name: init
        id: init
        run: |
          terraform init
        continue-on-error: false

      - name: apply
        id: apply
        run: terraform apply -auto-approve
